version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
          - "@mdx-js/react"
          - "prism-react-renderer"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      linting:
        patterns:
          - "@eslint/*"
          - "eslint*"
          - "globals"
          - "stylelint*"
          - "typescript-eslint"
      typescript:
        patterns:
          - "@types/node"
          - "typescript"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
