# @format

env:
  browser: true
  commonjs: true
  es2022: true
  node: true
extends:
  - eslint:recommended
  - airbnb
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - plugin:@docusaurus/recommended
settings:
  import/resolver:
    typescript: {}
  parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react-hooks
  - "@typescript-eslint"
  - "@docusaurus"
rules:
  {
    "semi": [2, "always"],
    "prefer-const": "error",
    "no-undef": 0,
    "global-require": 0,
    "no-await-in-loop": 0,
    "no-case-declarations": 1,
    "no-console": 0,
    "no-constant-binary-expression": 2,
    "no-continue": 0,
    "no-control-regex": 1,
    "no-else-return": [1, { allowElseIf: true }],
    "no-empty": [1, { allowEmptyCatch: true }],
    "no-lonely-if": 1,
    "no-nested-ternary": 1,
    "no-param-reassign": [1, { props: false }],
    "no-prototype-builtins": 1,
    "no-template-curly-in-string": 1,
    "no-unused-expressions": [1, { allowTaggedTemplates: true }],
    "no-useless-escape": 1,
    "no-void": [2, { allowAsStatement: true }],
    "prefer-destructuring": 1,
    "prefer-named-capture-group": 1,
    "prefer-template": 1,
    "jsx-a11y/click-events-have-key-events": 1,
    "jsx-a11y/no-noninteractive-element-interactions": 1,
    "react-hooks/rules-of-hooks": 2,
    "react-hooks/exhaustive-deps": 2,
    "react/jsx-filename-extension":
      [1, { extensions: [".js", ".jsx", ".ts", ".tsx"] }],
    "react/function-component-definition":
      [
        2,
        {
          namedComponents: "function-declaration",
          unnamedComponents: "arrow-function",
        },
      ],
    "react/jsx-props-no-spreading": 0,
    "react/jsx-key": [2, { checkFragmentShorthand: true }],
    "react/jsx-no-useless-fragment": [1, { allowExpressions: true }],
    "react/no-unstable-nested-components": [1, { allowAsProps: true }],
    "react/prefer-stateless-function": 1,
    "react/require-default-props": [2, { ignoreFunctionalComponents: true }],
    "@docusaurus/string-literal-i18n-messages": 2,
    "@docusaurus/no-untranslated-text":
      [1, { ignoredStrings: ["·", "—", "×"] }],
    "import/extensions": 0,
    "import/no-unresolved":
      [2, { "ignore": ["^@theme", "^@docusaurus", "^@site"] }],
    "import/order":
      [
        1,
        {
          groups:
            [
              "builtin",
              "external",
              "internal",
              ["parent", "sibling", "index"],
              "type",
            ],
          pathGroups:
            [
              {
                pattern: "*.+(css|sass|less|scss|pcss|styl)",
                group: "unknown",
                patternOptions: { matchBase: true },
                position: "after",
              },
              { pattern: "react", group: "builtin", position: "before" },
              { pattern: "clsx", group: "external", position: "before" },
              { pattern: "@theme/**", group: "internal" },
              { pattern: "@site/**", group: "internal" },
              { pattern: "@theme-init/**", group: "internal" },
              { pattern: "@theme-original/**", group: "internal" },
            ],
          pathGroupsExcludedImportTypes: [],
          warnOnUnassignedImports: true,
        },
      ],
    "import/prefer-default-export": 0,
    "@typescript-eslint/no-var-requires": 0,
  }
