env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - plugin:@docusaurus/recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - "@docusaurus"
  - "@typescript-eslint"
rules:
  {
    "no-undef": 0,
    "global-require": 0,
    "react/no-array-index-key": 0,
    "import/no-unresolved":
      [2, { "ignore": ["^@theme", "^@docusaurus", "^@site"] }],
    "react/jsx-filename-extension":
      [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
    "react/require-default-props":
      [
        1,
        {
          "forbidDefaultForRequired": false,
          "classes": "ignore",
          "functions": "ignore",
        },
      ],
  }
