extends:
  - stylelint-config-standard
  - stylelint-config-prettier
plugins:
  - stylelint-csstree-validator
ignoreFiles:
  - static/**

rules: {
    "csstree/validator": [
      true
    ],
    "selector-class-pattern": [
      false
    ],
    "alpha-value-notation": [
      "percentage",
      {
        "exceptProperties": [
          "opacity"
        ]
      }
    ],
    "at-rule-empty-line-before": null,
    "at-rule-name-case": null,
    "at-rule-name-space-after": null,
    "at-rule-no-vendor-prefix": [
      true
    ],
    "at-rule-semicolon-newline-after": null,
    "block-closing-brace-empty-line-before": null,
    "block-closing-brace-newline-after": null,
    "block-closing-brace-newline-before": null,
    "block-closing-brace-space-before": null,
    "block-opening-brace-newline-after": null,
    "block-opening-brace-space-after": null,
    "block-opening-brace-space-before": null,
    "color-function-notation": [
      "modern"
    ],
    "color-hex-case": null,
    "color-hex-length": [
      "short"
    ],
    "comment-empty-line-before": [
      "always",
      {
        "except": [
          "first-nested"
        ],
        "ignore": [
          "stylelint-commands"
        ]
      }
    ],
    "comment-whitespace-inside": [
      "always"
    ],
    "custom-property-empty-line-before": [
      "always",
      {
        "except": [
          "after-custom-property",
          "first-nested"
        ],
        "ignore": [
          "after-comment",
          "inside-single-line-block"
        ]
      }
    ],
    "custom-media-pattern": [
      "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$",
      {
        "message": "Expected custom media query name to be kebab-case"
      }
    ],
    "custom-property-pattern": [
      "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$",
      {
        "message": "Expected custom property name to be kebab-case"
      }
    ],
    "declaration-bang-space-after": null,
    "declaration-bang-space-before": null,
    "declaration-block-semicolon-newline-after": null,
    "declaration-block-semicolon-space-after": null,
    "declaration-block-semicolon-space-before": null,
    "declaration-block-single-line-max-declarations": [
      1
    ],
    "declaration-block-trailing-semicolon": null,
    "declaration-block-no-redundant-longhand-properties": [
      true
    ],
    "declaration-colon-newline-after": null,
    "declaration-colon-space-after": null,
    "declaration-colon-space-before": null,
    "declaration-empty-line-before": [
      "always",
      {
        "except": [
          "after-declaration",
          "first-nested"
        ],
        "ignore": [
          "after-comment",
          "inside-single-line-block"
        ]
      }
    ],
    "font-family-name-quotes": [
      "always-where-recommended"
    ],
    "function-comma-newline-after": null,
    "function-comma-space-after": null,
    "function-comma-space-before": null,
    "function-max-empty-lines": null,
    "function-name-case": [
      "lower"
    ],
    "function-parentheses-newline-inside": null,
    "function-parentheses-space-inside": null,
    "function-url-quotes": [
      "always"
    ],
    "function-whitespace-after": [
      "always"
    ],
    "hue-degree-notation": [
      "angle"
    ],
    "import-notation": [
      "string"
    ],
    "indentation": null,
    "keyframes-name-pattern": [
      "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$",
      {
        "message": "Expected keyframe name to be kebab-case"
      }
    ],
    "length-zero-no-unit": [
      true
    ],
    "max-empty-lines": null,
    "max-line-length": null,
    "media-feature-colon-space-after": null,
    "media-feature-colon-space-before": null,
    "media-feature-name-case": null,
    "media-feature-name-no-vendor-prefix": [
      true
    ],
    "media-feature-parentheses-space-inside": null,
    "media-feature-range-operator-space-after": [
      "always"
    ],
    "media-feature-range-operator-space-before": [
      "always"
    ],
    "media-query-list-comma-newline-after": null,
    "media-query-list-comma-space-after": null,
    "media-query-list-comma-space-before": null,
    "no-empty-first-line": null,
    "no-eol-whitespace": null,
    "no-missing-end-of-source-newline": null,
    "number-leading-zero": null,
    "number-max-precision": [
      4
    ],
    "number-no-trailing-zeros": null,
    "property-case": null,
    "property-no-vendor-prefix": [
      true
    ],
    "rule-empty-line-before": [
      "always-multi-line",
      {
        "except": [
          "first-nested"
        ],
        "ignore": [
          "after-comment"
        ]
      }
    ],
    "selector-attribute-brackets-space-inside": null,
    "selector-attribute-operator-space-after": null,
    "selector-attribute-operator-space-before": null,
    "selector-attribute-quotes": null,
    "selector-combinator-space-after": null,
    "selector-combinator-space-before": null,
    "selector-descendant-combinator-no-non-space": null,
    "selector-id-pattern": [
      "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$",
      {
        "message": "Expected id selector to be kebab-case"
      }
    ],
    "selector-list-comma-newline-after": null,
    "selector-list-comma-space-before": null,
    "selector-max-empty-lines": null,
    "selector-no-vendor-prefix": [
      true
    ],
    "selector-not-notation": [
      "complex"
    ],
    "selector-pseudo-class-case": null,
    "selector-pseudo-class-parentheses-space-inside": null,
    "selector-pseudo-element-case": null,
    "selector-pseudo-element-colon-notation": [
      "double"
    ],
    "selector-type-case": [
      "lower"
    ],
    "shorthand-property-no-redundant-values": [
      true
    ],
    "string-quotes": null,
    "unit-case": null,
    "value-keyword-case": [
      "lower"
    ],
    "value-list-comma-newline-after": null,
    "value-list-comma-space-after": null,
    "value-list-comma-space-before": null,
    "value-list-max-empty-lines": null,
    "value-no-vendor-prefix": [
      true
    ],
    "at-rule-no-unknown": [
      true
    ],
    "block-no-empty": [
      true
    ],
    "color-no-invalid-hex": [
      true
    ],
    "comment-no-empty": [
      true
    ],
    "custom-property-no-missing-var-function": [
      true
    ],
    "declaration-block-no-duplicate-custom-properties": [
      true
    ],
    "declaration-block-no-duplicate-properties": [
      true,
      {
        "ignore": [
          "consecutive-duplicates-with-different-values"
        ]
      }
    ],
    "declaration-block-no-shorthand-property-overrides": [
      true
    ],
    "font-family-no-duplicate-names": [
      true
    ],
    "font-family-no-missing-generic-family-keyword": [
      true
    ],
    "function-calc-no-unspaced-operator": [
      true
    ],
    "function-linear-gradient-no-nonstandard-direction": [
      true
    ],
    "function-no-unknown": [
      true
    ],
    "keyframe-block-no-duplicate-selectors": [
      true
    ],
    "keyframe-declaration-no-important": [
      true
    ],
    "media-feature-name-no-unknown": [
      true
    ],
    "named-grid-areas-no-invalid": [
      true
    ],
    "no-descending-specificity": [
      true
    ],
    "no-duplicate-at-import-rules": [
      true
    ],
    "no-duplicate-selectors": [
      true
    ],
    "no-empty-source": [
      true
    ],
    "no-extra-semicolons": null,
    "no-invalid-double-slash-comments": [
      true
    ],
    "no-invalid-position-at-import-rule": [
      true
    ],
    "no-irregular-whitespace": [
      true
    ],
    "property-no-unknown": [
      true
    ],
    "selector-pseudo-class-no-unknown": [
      true
    ],
    "selector-pseudo-element-no-unknown": [
      true
    ],
    "selector-type-no-unknown": [
      true,
      {
        "ignore": [
          "custom-elements"
        ]
      }
    ],
    "string-no-newline": [
      true
    ],
    "unit-no-unknown": [
      true
    ],
    "linebreaks": null,
    "at-rule-name-newline-after": null,
    "at-rule-semicolon-space-before": null,
    "block-closing-brace-space-after": null,
    "block-opening-brace-newline-before": null,
    "declaration-block-semicolon-newline-before": null,
    "function-comma-newline-before": null,
    "media-query-list-comma-newline-before": null,
    "selector-list-comma-newline-before": null,
    "selector-list-comma-space-after": null,
    "unicode-bom": null,
    "value-list-comma-newline-before": null
  }