extends:
  - stylelint-config-standard
  - stylelint-config-prettier
plugins:
  - stylelint-csstree-validator
ignoreFiles:
  - node_modules/**/*
  - static/**
rules:
  "csstree/validator": true
  "selector-class-pattern": false
