name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v4
    - name: ⎔ Setup node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: "lts/*"
        cache: "pnpm"
    - name: 🏗 Prepare
      shell: bash
      run: |
        pnpm i
        pnpm build:en
