name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
    - name: ⎔ Setup node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "22"
        cache: "pnpm"
    - name: 🏗 Prepare
      shell: bash
      run: NODE_ENV=development pnpm i --frozen-lockfile
