extends:
  - stylelint-config-standard
  - stylelint-config-css-modules
rules:
  no-descending-specificity: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: true
  keyframe-declaration-no-important: true
  color-no-invalid-hex: true
  color-no-hex: true
  color-function-notation: modern
  function-disallowed-list:
    - rgb
    - rgba
    - hwb
    - lab
    - lch
    - oklab
    - oklch
    - color
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
  block-no-empty: null
  selector-class-pattern: null
  custom-property-empty-line-before: null
  selector-id-pattern: null
  declaration-empty-line-before: null
  comment-empty-line-before: null
