import {
  faSpinner,
  faHeart,
  faCircleInfo,
  faListCheck,
  faDownload,
  faTerminal,
  faBook,
  faTools,
  faQuestionCircle,
  faWrench,
  faCog,
  faHashtag,
  faSlidersH,
  faSquareUpRight,
  faGears,
  faClockRotateLeft,
  faWandMagicSparkles,
  faWandSparkles,
  faFillDrip,
  faPowerOff,
  faLayerGroup,
  faPlug,
  faBolt,
  faCode,
  faList,
  faToggleOn,
  faCodeBranch,
  faKey,
  faCheckDouble,
  faSync,
} from "@fortawesome/free-solid-svg-icons";
import {faGithub, faGitAlt} from "@fortawesome/free-brands-svg-icons";
import {IconDefinition} from "@fortawesome/fontawesome-svg-core";

const iconMap: Record<string, IconDefinition> = {
  spinner: faSpinner,
  heart: faHeart,
  "circle-info": faCircleInfo,
  "list-check": faListCheck,
  github: faGithub,
  download: faDownload,
  terminal: faTerminal,
  book: faBook,
  tools: faTools,
  "question-circle": faQuestionCircle,
  wrench: faWrench,
  cog: faCog,
  hashtag: faHashtag,
  sliders: faSlidersH,
  "square-up-right": faSquareUpRight,
  "git-alt": faGitAlt,
  gears: faGears,
  "clock-rotate-left": faClockRotateLeft,
  "wand-magic-sparkles": faWandMagicSparkles,
  "wand-sparkles": faWandSparkles,
  "fill-drip": faFillDrip,
  "power-off": faPowerOff,
  "layer-group": faLayerGroup,
  plug: faPlug,
  bolt: faBolt,
  code: faCode,
  list: faList,
  "toggle-on": faToggleOn,
  "code-branch": faCodeBranch,
  key: faKey,
  "check-double": faCheckDouble,
  sync: faSync,
};

export default iconMap;
