# @format
---
name: "🔁 Rebase"

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    runs-on: ubuntu-latest
    name: 🔁 Rebase
    # Automate with comments: /autosquash, /rebase
    if: >-
      github.event.issue.pull_request != '' && (
        contains(github.event.comment.body, '/rebase') ||
        contains(github.event.comment.body, '/autosquash')
      )

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: 🔁 Rebase
        uses: z-shell/.github/actions/rebase@v1.0.7
        with:
          autosquash: ${{ contains(github.event.comment.body, '/autosquash') || contains(github.event.comment.body, '/rebase-autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
