---
name: "🌐 Crowdin Upload"

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "blog/**"
      - "community/**"
      - "ecosystem/**"
      - "src/pages/**"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: Crowdin
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Upload"
        uses: crowdin/github-action@7ca9c452bfe9197d3bb7fa83a4d7e2b0c9ae835d # v2.16.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          upload_sources_args: "--delete-obsolete"
