# @format
---
name: "🌐 Crowdin Download"

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    environment: Crowdin
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Download"
        uses: crowdin/github-action@b8012bd5491b8aa8578b73ab5b5f5e7c94aaa6e2 # v2.7.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: ${{ secrets.ACTIONS_USER }}
          github_user_email: ${{ secrets.ACTIONS_MAIL }}
