# @format
---
name: "🌐 Crowdin Download"

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    environment: Crowdin
    timeout-minutes: 30
    concurrency:
      group: ci-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Download"
        uses: crowdin/github-action@7ca9c452bfe9197d3bb7fa83a4d7e2b0c9ae835d # v2.16.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: ${{ secrets.ACTIONS_USER }}
          github_user_email: ${{ secrets.ACTIONS_MAIL }}
