---
name: Crowdin Upload

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "blog/**"
      - "community/**"
      - "ecosystem/**"
      - "src/pages/**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: Crowdin
    timeout-minutes: 10
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Upload"
        uses: crowdin/github-action@52aa776766211d83d975df51f3b9c53c2f8ba35f # v2.16.3
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          upload_sources_args: "--delete-obsolete"
