# @format
---
name: "🌐 Crowdin Download"

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Download"
        uses: crowdin/github-action@1.4.11
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: digital-teams[bot]
          github_user_email: actions@zshell.dev
