---
name: "🌐 Crowdin Download"

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  download:
    runs-on: ubuntu-latest
    environment: Crowdin
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v6.0.0
        with:
          fetch-depth: 0
      - name: "🚀 Crowdin Download"
        uses: crowdin/github-action@94397c43f77e830d1f12f6bb031afdd8d8620731 # v2.16.2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          github_user_name: ${{ secrets.ACTIONS_USER }}
          github_user_email: ${{ secrets.ACTIONS_MAIL }}
