---
name: 🔖 Pull Request Labeler
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Labeler
        uses: actions/labeler@4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: false
