# @format
---
name: 🔖 Pull Request Labeler
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: project-automation
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GH_PAT }}"
          sync-labels: true
