---
name: "✅ Lychee"

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  workflow_call: {}
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [main]
    paths:
      - "**.md"
      - "**.mdx"
  pull_request_target:
    branches: [main]
    paths:
      - "**.md"
      - "**.mdx"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "📤 Restore cache"
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: "📊 Lychee Link Checker"
        id: lychee
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        with:
          args: --config ./.github/lychee.toml --base . --verbose --no-progress './**/*.md*'
          format: markdown
          output: ./.github/LINKS_REPORT.md
          fail: false
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "🔖 Create Issue From File"
        if: env.lychee_exit_code != 0
        id: lychee-report
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5
        with:
          title: " 📢 Link Checker Report"
          content-filepath: ./.github/LINKS_REPORT.md
          labels: maintenance 📈
          issue-number: 405
