---
name: Deploy Wiki
on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  URL: "https://wiki.zshell.dev"

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploying
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://wiki.zshell.dev"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: "📦 Setup pnpm"
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          require-lockfile: true
      - name: "🏗  Build"
        run: pnpm run build
        env:
          NODE_ENV: development
      - name: "🚀 Publish"
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy build --project-name=zsh
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
