---
name: "🛳  Deploy Wiki"
on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  URL: "https://wiki.zshell.dev"
  STYLES: ${{ secrets.FA_STYLES_KIT }}

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🛳  Deploying
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: "📦 Setup pnpm"
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: "⎔  Setup node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: "🏗  Build"
        run: pnpm i --prod --frozen-lockfile && pnpm run build
      - name: "🚀 Publish"
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          projectName: "zsh"
          directory: "build"
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
