---
name: "🛳  Deploy Wiki"
on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  URL: "https://wiki.zshell.dev"
  STYLES: ${{ secrets.FA_STYLES_KIT }}

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🛳  Deploying
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "📦 Setup pnpm"
        uses: pnpm/action-setup@v4
      - name: "⎔  Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: "🏗  Build"
        run: pnpm i --frozen-lockfile && pnpm run build
        env:
          NODE_ENV: development
      - name: "🚀 Publish"
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy build --project-name=zsh
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
