# @format
---
name: 🏷️ Verify PR Labels

on:
  pull_request_target:
    types: ["opened", "labeled", "unlabeled", "synchronize"]
  workflow_dispatch: {}

jobs:
  labels:
    name: "🏷️"
    uses: z-shell/.github/.github/workflows/pr-labels.yml@3e21fd8ea5d818c5fc6149cac9357b1502260d5f # main
