---
name: "🔄 Rclone"
on:
  push:
    branches: [main]
    paths:
      - "static/**"
      - ".github/workflows/rclone-action.yml"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  sync:
    if: github.repository == 'z-shell/wiki'
    runs-on: ubuntu-latest
    environment: R2
    env:
      img_local_path: "static/img"
      img_remote_path: "r2store:r2-store/img"
      assets_local_path: "static/assets"
      assets_remote_path: "r2store:r2-store/assets"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: "⏫ Run rclone/r2-store/img"
        uses: z-shell/.github/actions/rclone@3e21fd8ea5d818c5fc6149cac9357b1502260d5f # main
        with:
          config: ${{ secrets.R2_STORE }}
          args: "copy ${{ env.img_local_path }} ${{ env.img_remote_path }}"
          debug: false
      - name: "⏫ Run rclone/r2-store/assets"
        uses: z-shell/.github/actions/rclone@3e21fd8ea5d818c5fc6149cac9357b1502260d5f # main
        with:
          config: ${{ secrets.R2_STORE }}
          args: "copy ${{ env.assets_local_path }} ${{ env.assets_remote_path }}"
          debug: false
