---
name: Trunk Code Quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Trunk Code Quality
    permissions:
      actions: read
      checks: write
      contents: read
    uses: z-shell/.github/.github/workflows/trunk.yml@2d96d0f7973270435e8a607256346b8c2251d409 # main
    with:
      cache: false
      setup-deps: true
